/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/Big Building.glb -o src/components/Building.jsx -k -K -r public 
Big Building by Quaternius
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Building(props) {
  const { nodes, materials } = useGLTF('/Models/Big Building.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Building3_Big" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="Building3_Big_1" geometry={nodes.Building3_Big_1.geometry} material={materials.BrickRed} />
            <mesh name="Building3_Big_2" geometry={nodes.Building3_Big_2.geometry} material={materials.Beige} />
            <mesh name="Building3_Big_3" geometry={nodes.Building3_Big_3.geometry} material={materials.LightYellow} />
            <mesh name="Building3_Big_4" geometry={nodes.Building3_Big_4.geometry} material={materials.Brown} />
            <mesh name="Building3_Big_5" geometry={nodes.Building3_Big_5.geometry} material={materials.DarkGrey} />
            <mesh name="Building3_Big_6" geometry={nodes.Building3_Big_6.geometry} material={materials.Grey} />
            
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Big Building.glb')
