/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/house.gltf -o src/components/House.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function House(props) {
  const { nodes, materials } = useGLTF('/Models/house.gltf')
  return (
    <group {...props} dispose={null} position={[0,.5,0]}>
      <group name="Scene">
        <group name="house_type04">
          <mesh name="Mesh_house_type04" geometry={nodes.Mesh_house_type04.geometry} material={materials.border} />
          <mesh name="Mesh_house_type04_1" geometry={nodes.Mesh_house_type04_1.geometry} material={materials.door} />
          <mesh name="Mesh_house_type04_2" geometry={nodes.Mesh_house_type04_2.geometry} material={materials.wndow} />
          <mesh name="Mesh_house_type04_3" geometry={nodes.Mesh_house_type04_3.geometry} material={materials.roof} />
          <mesh name="Mesh_house_type04_4" geometry={nodes.Mesh_house_type04_4.geometry} material={materials.main} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/house.gltf')
