/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/house2.gltf -o src/components/House2.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function House2(props) {
  const { nodes, materials } = useGLTF('/Models/house2.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="house_type08">
          <mesh name="Mesh_house_type08" geometry={nodes.Mesh_house_type08.geometry} material={materials.border} />
          <mesh name="Mesh_house_type08_1" geometry={nodes.Mesh_house_type08_1.geometry} material={materials.window} />
          <mesh name="Mesh_house_type08_2" geometry={nodes.Mesh_house_type08_2.geometry} material={materials.main} />
          <mesh name="Mesh_house_type08_3" geometry={nodes.Mesh_house_type08_3.geometry} material={materials.roof} />
          <mesh name="Mesh_house_type08_4" geometry={nodes.Mesh_house_type08_4.geometry} material={materials.door} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/house2.gltf')
