/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/Brain2.glb -o src/components/Brain.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshPhysicalMaterial } from 'three'

export function Brain(props) {
  const { nodes, materials } = useGLTF('/Models/Brain2.glb')
  const material = new MeshPhysicalMaterial({color: '#b56b76'})
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh castShadow receiveShadow name="Left" geometry={nodes.Object.geometry} material={material} rotation={[1.584, 0, 0]} scale={3.586} />
        <mesh castShadow receiveShadow name="Right" geometry={nodes.Brain_Part_06.geometry} material={material} rotation={[1.584, 0, 0]} scale={3.586} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Brain2.glb')
