/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/Glasses.glb -o src/components/Glasses.jsx -k -K -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Glasses(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Models/Glasses.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['Eye1'].play()
    actions['Eye2'].play()
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Glasses" geometry={nodes.Glasses.geometry} material={materials.M_Glasses} />
        <mesh name="Glasses_2" geometry={nodes.Glasses_2.geometry} material={materials.M_Glasses} position={[0.059, 0, 0.048]} />
        <mesh name="Glasses_1" geometry={nodes.Glasses_1.geometry} material={materials.M_Glasses} position={[-0.059, 0, 0.048]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Material} position={[-0.031, 0.001, 0.033]} rotation={[0.062, 1.546, 1.501]} scale={0.022} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.Material} position={[0.032, 0.001, 0.033]} rotation={[3.052, 1.554, -1.489]} scale={0.022} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[-0.032, 0, 0.078]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={-0.022} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.002']} position={[0.031, 0, 0.079]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={-0.023} />
        <mesh name="Eye1" geometry={nodes.Eye1.geometry} material={materials['Material.001']} position={[-0.032, 0, 0.064]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={-0.006} />
        <mesh name="Eye2" geometry={nodes.Eye2.geometry} material={materials['Material.001']} position={[0.032, 0, 0.065]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={-0.006} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Glasses.glb')
