/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/Pool.glb -o src/components/Pool.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pool(props) {
  const { nodes, materials } = useGLTF('/Models/Pool.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cap_1" geometry={nodes.Cap_1.geometry} material={materials.Metal} position={[1.993, 0.964, -2.087]} scale={0.016} />
        <mesh name="Cap_2" geometry={nodes.Cap_2.geometry} material={materials.Metal} position={[2.471, 0.964, -2.087]} scale={0.016} />
        <mesh name="Cap_3" geometry={nodes.Cap_3.geometry} material={materials.Metal} position={[1.994, 0.478, -2.039]} rotation={[Math.PI / 2, 0, 0]} scale={[0.016, 0.017, 0.016]} />
        <mesh name="Cap_4" geometry={nodes.Cap_4.geometry} material={materials.Metal} position={[2.471, 0.478, -2.036]} rotation={[Math.PI / 2, 0, 0]} scale={0.016} />
        <mesh name="Filrer_2" geometry={nodes.Filrer_2.geometry} material={materials['Material.003']} position={[-1.497, 1.004, 2.145]} scale={[0.177, 0.269, 0.11]} />
        <mesh name="Filter_1" geometry={nodes.Filter_1.geometry} material={materials['Material.003']} position={[1.518, 1.004, -2.145]} scale={[0.179, 0.264, 0.111]} />
        <group name="Lamp_1" position={[2.994, 0.402, 0]}>
          <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.007']} />
          <mesh name="Sphere_1" geometry={nodes.Sphere_1.geometry} material={materials['Material.001']} />
        </group>
        <group name="Lamp_2" position={[1.002, 0.402, 1.994]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={materials['Material.007']} />
          <mesh name="Sphere003_1" geometry={nodes.Sphere003_1.geometry} material={materials['Material.001']} />
        </group>
        <group name="Lamp_3" position={[-1.01, 0.402, 1.994]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.007']} />
          <mesh name="Sphere002_1" geometry={nodes.Sphere002_1.geometry} material={materials['Material.001']} />
        </group>
        <group name="Lamp_4" position={[-2.994, 0.402, 0]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.007']} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials['Material.001']} />
        </group>
        <group name="Lamp_5" position={[-1.007, 0.402, -1.994]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={materials['Material.007']} />
          <mesh name="Sphere005_1" geometry={nodes.Sphere005_1.geometry} material={materials['Material.001']} />
        </group>
        <group name="Lamp_6" position={[1.002, 0.402, -1.994]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={materials['Material.007']} />
          <mesh name="Sphere004_1" geometry={nodes.Sphere004_1.geometry} material={materials['Material.001']} />
        </group>
        <group name="Pool_Main">
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Tiles} />
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.Rim} />
          <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.Filling} />
          <mesh name="Cube001_3" geometry={nodes.Cube001_3.geometry} material={materials.Cement} />
          <mesh name="Cube001_4" geometry={nodes.Cube001_4.geometry} material={materials['Tiles.001']} />
        </group>
        <mesh name="Rail_1" geometry={nodes.Rail_1.geometry} material={materials.Metal} position={[1.993, 1.71, -1.795]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh name="Rail_2" geometry={nodes.Rail_2.geometry} material={materials.Metal} position={[2.471, 1.71, -1.795]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh name="Step_1" geometry={nodes.Step_1.geometry} material={materials.Material} position={[0, 0.092, 0]} />
        <mesh name="Step_2" geometry={nodes.Step_2.geometry} material={materials.Material} position={[0, -0.054, 0]} />
        <mesh name="Step_3" geometry={nodes.Step_3.geometry} material={materials.Material} position={[0, -0.19, 0]} />
        <group name="Trampolin" position={[-4.511, 1.228, 0]} rotation={[0, -1.571, 0]} scale={0.23}>
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.005']} />
          <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials['Material.009']} />
        </group>
        <mesh name="Water_Main" geometry={nodes.Water_Main.geometry} material={materials['Material.002']} position={[-0.042, 0.956, -0.03]} scale={[.12,.12,.1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Pool.glb')
